# Generated by Django 4.0.5 on 2022-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('delivery_date', models.DateField(verbose_name='Срок поставки')),
                ('price_dollars', models.FloatField(verbose_name='Цена в долларах $')),
                ('price_rubles', models.FloatField(verbose_name='Цена в рублях ₽')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
