version: '3.7'
services:
  web:
    container_name: web
    build: ./
    command: "gunicorn --bind 0.0.0.0:${DJANGO_PORT} SyncGoogleSheets.wsgi"
    env_file:
      - ./.env
    expose:
      - ${DJANGO_PORT}
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  db:

